# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:10
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章标题', max_length=124, verbose_name='标题')),
                ('head_pic_url', models.CharField(default='/static/img/default.jpg', help_text='主页头图', max_length=256, verbose_name='头图链接')),
                ('pub_time', models.DateTimeField(auto_now_add=True, help_text='发布时间')),
                ('brief', models.CharField(blank=True, help_text='文章摘要', max_length=256, null=True, verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(help_text='博客正文', verbose_name='正文')),
                ('page_views', models.PositiveIntegerField(default=0, editable=False, help_text='博客访问量', verbose_name='访问量')),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_1', models.CharField(db_index=True, help_text='种类1', max_length=32, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_2', models.CharField(db_index=True, help_text='种类2', max_length=32, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='友情链接名称', max_length=64, unique=True)),
                ('friend_url', models.CharField(default='http://', max_length=256, verbose_name='链接')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Friend_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, help_text='好友标签', max_length=32, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='博客标题', max_length=124, verbose_name='标题')),
                ('head_pic_url', models.CharField(default='/static/img/default.jpg', help_text='主页头图', max_length=256, verbose_name='头图链接')),
                ('pub_time', models.DateTimeField(auto_now_add=True, help_text='发布时间')),
                ('brief', models.CharField(blank=True, help_text='文章摘要', max_length=256, null=True, verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(help_text='博客正文', verbose_name='正文')),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, help_text='文章标签', max_length=32, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='添加时间')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogApp.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='friend',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blogApp.Friend_Tags', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.Category1', verbose_name='一级目录'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.Category2', verbose_name='二级目录'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogApp.Tag', verbose_name='标签'),
        ),
    ]
